const ActionTypes = {
	ADD_CONTACT: 'ADD_CONTACT'
,	DELETE_CONTACT: 'DELETE_CONTACT'
,	UPDATE_CONTACT: 'UPDATE_CONTACT'
,	SET_CONTACTS: 'SET_CONTACTS'
,	SELECT_CONTACT: 'SELECT_CONTACT'
,	UNSELECT_CONTACT: 'UNSELECT_CONTACT'
,	DELETE_SELECTED_CONTACTS: 'DELETE_SELECTED_CONTACTS'
};

export default ActionTypes;